[workspace]
resolver = "2"
members = [
    "rhombus",
    "rhombus-build",
    "rhombus-cli",
    "examples/standalone",
    "examples/plugin",
    "examples/external-plugin",
    "examples/demo",
]

[profile.release]
strip = true
panic = "abort"
# opt-level = "s"
# lto = "fat"
# codegen-units = 1
