[workspace]
resolver = "2"
members = [
    "rhombus",
    "rhombus-cli",
    "examples/standalone",
    "examples/plugin",
    "examples/external-plugin",
    "examples/demo",
]

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
