# yaml-language-server: $schema=https://raw.githubusercontent.com/rhombusgg/rhombus/main/schema.json
title: Custom GRPC example
location_url: http://localhost:3000
auth:
  - credentials
jwt_secret: 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
