/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Author {
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    #[serde(rename = "discord_id")]
    pub discord_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl Author {
    pub fn new(avatar_url: String, discord_id: String, name: String) -> Author {
        Author {
            avatar_url,
            discord_id,
            name,
        }
    }
}

