/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengePatch {
    #[serde(rename = "author", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author: Option<Option<Box<models::PatchForString>>>,
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<Box<models::PatchForString>>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<Box<models::PatchForString>>>,
    #[serde(rename = "files", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub files: Option<Option<Box<models::PatchForArrayOfChallengeAttachment>>>,
    #[serde(rename = "flag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag: Option<Option<Box<models::PatchForString>>>,
    #[serde(rename = "healthscript", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub healthscript: Option<Option<Box<models::PatchForNullableString>>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<Box<models::PatchForString>>>,
    #[serde(rename = "ticket_template", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ticket_template: Option<Option<Box<models::PatchForNullableString>>>,
}

impl ChallengePatch {
    pub fn new() -> ChallengePatch {
        ChallengePatch {
            author: None,
            category: None,
            description: None,
            files: None,
            flag: None,
            healthscript: None,
            name: None,
            ticket_template: None,
        }
    }
}

