/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeDataPatchActionOneOf1 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ChallengeDataPatchActionOneOf1 {
    pub fn new(id: String, r#type: Type) -> ChallengeDataPatchActionOneOf1 {
        ChallengeDataPatchActionOneOf1 {
            id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "delete_challenge")]
    DeleteChallenge,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeleteChallenge
    }
}

