/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChallengeDataPatchActionOneOf8 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "value")]
    pub value: Box<models::Category>,
}

impl ChallengeDataPatchActionOneOf8 {
    pub fn new(id: String, r#type: Type, value: models::Category) -> ChallengeDataPatchActionOneOf8 {
        ChallengeDataPatchActionOneOf8 {
            id,
            r#type,
            value: Box::new(value),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "create_category")]
    CreateCategory,
}

impl Default for Type {
    fn default() -> Type {
        Self::CreateCategory
    }
}

