/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchForString {
    #[serde(rename = "new")]
    pub new: String,
    #[serde(rename = "old")]
    pub old: String,
}

impl PatchForString {
    pub fn new(new: String, old: String) -> PatchForString {
        PatchForString {
            new,
            old,
        }
    }
}

