/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchForArrayOfChallengeAttachment {
    #[serde(rename = "new")]
    pub new: Vec<models::ChallengeAttachment>,
    #[serde(rename = "old")]
    pub old: Vec<models::ChallengeAttachment>,
}

impl PatchForArrayOfChallengeAttachment {
    pub fn new(new: Vec<models::ChallengeAttachment>, old: Vec<models::ChallengeAttachment>) -> PatchForArrayOfChallengeAttachment {
        PatchForArrayOfChallengeAttachment {
            new,
            old,
        }
    }
}

