/*
 * rhombus_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchForNullableString {
    #[serde(rename = "new", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new: Option<Option<String>>,
    #[serde(rename = "old", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub old: Option<Option<String>>,
}

impl PatchForNullableString {
    pub fn new() -> PatchForNullableString {
        PatchForNullableString {
            new: None,
            old: None,
        }
    }
}

