name: Build Docs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: arduino/setup-protoc@v3
        with:
          version: "28.x"

      - uses: arduino/setup-protoc@v3
        with:
          version: "28.x"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: deno install

      - name: Build with VitePress
        run: deno task docs:build
